const $ = (selector) => document.querySelector(selector);
const $$ = (selector) => [...document.querySelectorAll(selector)];
const state = { data: { plaques: [], orders: [], messages: [], lots: [], stock: [], metrics: {} }, analytics: null, user: null, csrfToken: null, selectedCode: null };

async function api(path, options = {}) {
  const headers = { 'Content-Type': 'application/json', ...(options.headers || {}) }; if (state.csrfToken) headers['X-CSRF-Token'] = state.csrfToken;
  const response = await fetch(path, { ...options, headers });
  const payload = await response.json();
  if (response.status === 401) { showLogin(); throw new Error('Authentification requise.'); }
  if (!response.ok) throw new Error(payload.error || 'Erreur serveur');
  return payload;
}
function saleClass(sale) { return sale.includes('non') ? 'amber' : sale.includes('Vendue') || sale.includes('Payee') ? 'green' : 'gray'; }
function escapeHtml(value = '') { return String(value).replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[char])); }
function showLogin() { $('#login-backdrop').hidden = false; $('#login-password').focus(); }
function hideLogin() { $('#login-backdrop').hidden = true; }
function showToast(text) { const toast = $('#toast'); toast.textContent = text; toast.classList.add('show'); setTimeout(() => toast.classList.remove('show'), 2600); }

function renderPlaques() {
  const query = $('#plaque-search').value.toLowerCase(); const lifecycle = $('#status-filter').value; const category = $('#category-filter').value;
  const rows = state.data.plaques.filter((plaque) => (!query || Object.values(plaque).join(' ').toLowerCase().includes(query)) && (lifecycle === 'all' || plaque.lifecycle === lifecycle) && (category === 'all' || plaque.type === category));
  $('#plaque-body').innerHTML = rows.map((plaque) => `<tr><td><input type="checkbox" aria-label="Sélectionner ${escapeHtml(plaque.code)}"></td><td class="code">${escapeHtml(plaque.code)}</td><td><span class="pill gray">${escapeHtml(plaque.type)}</span></td><td><span class="pill ${saleClass(plaque.lifecycle_label)}">${escapeHtml(plaque.lifecycle_label)}</span></td><td>${escapeHtml(plaque.date)}</td><td>${escapeHtml(plaque.client)}</td><td class="destination">${escapeHtml(plaque.destination)}</td><td><strong>${plaque.scans}</strong></td><td><button class="row-action" data-config="${escapeHtml(plaque.code)}">Configurer</button></td></tr>`).join('') || '<tr><td colspan="9" class="empty">Aucune plaque ne correspond à ces critères.</td></tr>';
  $$('[data-config]').forEach((button) => button.addEventListener('click', () => openModal(state.data.plaques.find((plaque) => plaque.code === button.dataset.config))));
}
function renderMessages() { $('#message-body').innerHTML = state.data.messages.map((message) => `<tr><td>${escapeHtml(message.client)}</td><td class="code">${escapeHtml(message.code)}</td><td>${message.month}</td><td>${message.total}</td><td>${escapeHtml(message.last)}</td></tr>`).join(''); $('#message-notice').textContent = `${state.data.messages.filter((message) => message.last === 'jamais').length} clients sans numéro WhatsApp. Ajoutez le numéro dans la fiche de la plaque.`; }
function renderLots() { $('#lot-body').innerHTML = state.data.lots.map((lot) => `<tr><td><strong>${escapeHtml(lot.type)}</strong></td><td>${lot.plaques}</td><td>${lot.active}</td><td>${lot.free}</td><td><span class="pill ${lot.state === 'Bas' ? 'amber' : 'green'}">${lot.state}</span></td></tr>`).join(''); }
function renderOrders() { const query = $('#order-search').value.toLowerCase(); const selectedStatus = $('#order-tabs .active').dataset.orderStatus; const orders = state.data.orders.filter((order) => (selectedStatus === 'all' || order.status === selectedStatus) && (!query || Object.values(order).join(' ').toLowerCase().includes(query))); $('#order-list').innerHTML = orders.map((order) => `<article class="order-card"><div><h3>${escapeHtml(order.code)} <span class="pill amber">Annulée</span></h3><p>${escapeHtml(order.date)} · Source : test-email</p></div><div><h3>${escapeHtml(order.name)}</h3><p>${escapeHtml(order.phone)} · Remise en main propre à Nabeul</p></div><div><h3>${escapeHtml(order.price)}</h3><p>1 plaque · livraison offerte</p></div><a class="text-btn" href="https://wa.me/21656680248" target="_blank" rel="noreferrer">WhatsApp ↗</a></article>`).join('') || '<div class="panel">Aucune commande ici.</div>'; }
function renderStock() { $('#stock-grid').innerHTML = state.data.stock.map((item) => `<div class="stock-item ${item.low ? 'low' : ''}"><strong>${item.count}</strong><small>${escapeHtml(item.type)} · ${item.low ? 'Bas' : 'OK'}</small></div>`).join(''); }
function renderMetrics() { const { active, free, scans } = state.data.metrics; document.querySelector('.metric-card:nth-child(1) strong').textContent = active; document.querySelector('.metric-card:nth-child(2) strong').textContent = free; document.querySelector('.metric-card:nth-child(3) strong').textContent = scans.toLocaleString('fr-FR'); $('.nav-count').textContent = state.data.metrics.total; }
function renderAnalytics() { const analytics = state.analytics || { total: 0, daily: [], devices: {}, referrers: {} }; $('#analytics-total').textContent = analytics.total; const max = Math.max(...analytics.daily.map((item) => item.scans), 1); $('#analytics-bars').innerHTML = analytics.daily.slice(-14).map((item) => `<div class="analytics-bar"><span style="height:${Math.max(8, item.scans / max * 100)}%" title="${item.date}: ${item.scans} scans"></span><small>${item.date.slice(5)}</small></div>`).join('') || '<span class="analytics-empty">Aucun scan sur cette période.</span>'; $('#analytics-breakdown').innerHTML = Object.entries(analytics.devices).map(([key, value]) => `<span><b>${value}</b> ${escapeHtml(key)}</span>`).join(''); }

function openModal(plaque) { state.selectedCode = plaque.code; $('#modal-title').textContent = `Plaque ${plaque.code}`; $('#form-url').value = `${location.origin}/qrcode/${plaque.code}`; $('#form-destination').value = plaque.destination; $('#form-category').value = plaque.type; $('#form-lifecycle').value = plaque.lifecycle; $('#form-client').value = plaque.client; $('#form-phone').value = plaque.phone; $('#form-note').value = plaque.note || ''; $('#form-qr').src = `${plaque.qr_image_url}?t=${Date.now()}`; $('#download-qr').href = plaque.qr_image_url; $('#download-qr-svg').href = plaque.qr_svg_url; $('#download-qr-pdf').href = plaque.qr_pdf_url; $('#download-qr').download = `${plaque.code}.png`; $('#download-qr-svg').download = `${plaque.code}.svg`; $('#download-qr-pdf').download = `${plaque.code}.pdf`; $('#modal-backdrop').hidden = false; }
function closeModal() { $('#modal-backdrop').hidden = true; }
function closeCreateModal() { $('#create-backdrop').hidden = true; }

async function refresh() { state.data = await api('/api/dashboard'); state.analytics = await api(`/api/analytics?days=${$('#analytics-days').value}`); renderMetrics(); renderPlaques(); renderMessages(); renderLots(); renderOrders(); renderStock(); renderAnalytics(); }
async function downloadExport() { const response = await fetch('/api/export'); if (!response.ok) { showToast('Export réservé à l’administrateur.'); return; } const blob = await response.blob(); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = 'onpoint-export.json'; link.click(); URL.revokeObjectURL(link.href); }
function applyRole() { $('#user-role').textContent = `${state.user.label} · ${state.user.username}`; $$('.admin-only').forEach((element) => { element.hidden = state.user.role !== 'admin'; }); }

$('#login-form').addEventListener('submit', async (event) => { event.preventDefault(); $('#login-error').textContent = ''; try { state.user = await api('/api/login', { method: 'POST', body: JSON.stringify({ username: $('#login-username').value, password: $('#login-password').value }) }); state.csrfToken = state.user.csrf_token; hideLogin(); applyRole(); await refresh(); } catch (error) { $('#login-error').textContent = error.message; } });
$('#logout-btn').addEventListener('click', async () => { await api('/api/logout', { method: 'POST' }); state.user = null; state.csrfToken = null; showLogin(); });
$('#export-btn').addEventListener('click', downloadExport);
$('#analytics-days').addEventListener('change', async () => { state.analytics = await api(`/api/analytics?days=${$('#analytics-days').value}`); renderAnalytics(); });
$$('.nav-item').forEach((button) => button.addEventListener('click', () => { $$('.nav-item').forEach((item) => item.classList.remove('active')); button.classList.add('active'); $$('.view').forEach((view) => view.classList.remove('active-view')); $(`#${button.dataset.view}-view`).classList.add('active-view'); $('#page-title').innerHTML = button.dataset.view === 'plaques' ? 'OnPoint <span>/qrcode</span>' : 'Commandes'; }));
$('#plaque-search').addEventListener('input', renderPlaques); $('#status-filter').addEventListener('change', renderPlaques); $('#category-filter').addEventListener('change', renderPlaques); $('#order-search').addEventListener('input', renderOrders); $$('#order-tabs button').forEach((button) => button.addEventListener('click', () => { $$('#order-tabs button').forEach((item) => item.classList.remove('active')); button.classList.add('active'); renderOrders(); }));
$('#clients-btn').addEventListener('click', () => showToast('La vue clients est disponible via les rappels du mois.')); $('#due-btn').addEventListener('click', () => showToast('Les clients sans WhatsApp sont signalés dans cette liste.')); $('#create-btn').addEventListener('click', () => { $('#create-backdrop').hidden = false; $('#create-quantity').focus(); }); $('#modal-close').addEventListener('click', closeModal); $('#cancel-modal').addEventListener('click', closeModal); $('#create-close').addEventListener('click', closeCreateModal); $('#cancel-create').addEventListener('click', closeCreateModal);
$('#plaque-form').addEventListener('submit', async (event) => { event.preventDefault(); try { await api(`/api/plaques/${state.selectedCode}`, { method: 'PATCH', body: JSON.stringify({ destination: $('#form-destination').value, type: $('#form-category').value, lifecycle: $('#form-lifecycle').value, client: $('#form-client').value, phone: $('#form-phone').value, note: $('#form-note').value }) }); closeModal(); await refresh(); showToast('Plaque enregistrée.'); } catch (error) { showToast(error.message); } });
$('#create-form').addEventListener('submit', async (event) => { event.preventDefault(); try { const result = await api('/api/plaques', { method: 'POST', body: JSON.stringify({ quantity: Number($('#create-quantity').value), type: $('#create-category').value }) }); closeCreateModal(); await refresh(); showToast(`${result.count} codes QR uniques créés.`); } catch (error) { showToast(error.message); } });

(async () => { const sessionInfo = await fetch('/api/session').then((response) => response.json()); if (sessionInfo.authenticated) { state.user = sessionInfo.user; state.csrfToken = sessionInfo.csrf_token; hideLogin(); applyRole(); await refresh(); } else showLogin(); })();
